# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendchannels',
            old_name='friend',
            new_name='user',
        ),
    ]
