# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannels',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userchannels',
            name='modified',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
