# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171229_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchannels',
            name='friend',
        ),
        migrations.AddField(
            model_name='userchannels',
            name='friend',
            field=models.ManyToManyField(related_name='FriendChannel', to='users.FriendChannels'),
        ),
    ]
