
import { NgModule } from '@angular/core';
import { 
  MdButtonModule, 
  MdCheckboxModule, 
  MdCardModule, 
  MdMenuModule, 
  MdToolbarModule, 
  MdIconModule,
  MdInputModule,
  MdProgressSpinnerModule,
  MdTabsModule,
  MdSnackBarModule,
  MdListModule,
  
} from '@angular/material';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
// import {CdkTableModule} from '@angular/cdk';
// import {
//   MdAutocompleteModule,
//   MdButtonModule,
//   MdButtonToggleModule,
//   MdCardModule,
//   MdCheckboxModule,
//   MdChipsModule,
//   MdCoreModule,
//   MdDatepickerModule,
//   MdDialogModule,
//   MdExpansionModule,
//   MdIconModule,
//   MdInputModule,
//   MdListModule,
//   MdMenuModule,
//   MdNativeDateModule,
//   MdPaginatorModule,
//   MdProgressBarModule,
//   MdProgressSpinnerModule,
//   MdRadioModule,
//   MdRippleModule,
//   MdSelectModule,
//   MdSidenavModule,
//   MdSliderModule,
//   MdSlideToggleModule,
//   MdSnackBarModule,
//   MdSortModule,
//   MdTableModule,
//   MdTabsModule,
//   MdToolbarModule,
//   MdTooltipModule,
// } from '@angular/material';

@NgModule({
  // imports: [BrowserAnimationsModule, MdButtonModule, MdCheckboxModule, MdCardModule, MdMenuModule, MdToolbarModule, MdIconModule],
  // exports: [BrowserAnimationsModule, MdButtonModule, MdCheckboxModule, MdCardModule, MdMenuModule, MdToolbarModule, MdIconModule],
   exports: [
    BrowserAnimationsModule,
    // CdkTableModule,
    // MdAutocompleteModule,
    MdButtonModule,
    MdMenuModule,
    // MdButtonToggleModule,
    MdCardModule,
    // MdCheckboxModule,
    // MdChipsModule,
    // MdCoreModule,
    // MdDatepickerModule,
    // MdDialogModule,
    // MdExpansionModule,
    // MdGridListModule,
    MdIconModule,
    MdInputModule,
    // MdListModule,
    MdListModule,
    // MdNativeDateModule,
    // MdPaginatorModule,
    // MdProgressBarModule,
    MdProgressSpinnerModule,
    // MdRadioModule,
    // MdRippleModule,
    // MdSelectModule,
    // MdSidenavModule,
    // MdSliderModule,
    // MdSlideToggleModule,
    MdSnackBarModule,
    // MdSortModule,
    // MdTableModule,
    MdTabsModule,
    MdToolbarModule,
    // MdTooltipModule,
  ]
})
export class MyOwnCustomMaterialModule { }